module.exports = {
    WIDTH_DESKTOP_MAX: 1280,
    WIDTH_TABLET_MAX: 768,
    WIDTH_DESKTOP_INIT_COUNT: 12,
    WIDTH_DESKTOP_LOADING_COUNT: 12,
    WIDTH_TABLET_INIT_COUNT: 8,
    WIDTH_TABLET_LOADING_COUNT: 8,
    WIDTH_MOBILE_INIT_COUNT: 5,
    WIDTH_MOBILE_LOADING_COUNT: 2,
};