module.exports = {
    WIDTH_DESKTOP_MAX: 1280,
    WIDTH_TABLET_MAX: 768,
    CARDS_DESKTOP_INIT_COUNT: 12,
    CARDS_DESKTOP_LOADING_COUNT: 12,
    CARDS_TABLET_INIT_COUNT: 8,
    CARDS_TABLET_LOADING_COUNT: 8,
    CARDS_MOBILE_INIT_COUNT: 5,
    CARDS_MOBILE_LOADING_COUNT: 2,
};